"""Offline fallback question bank — used when the AI is unreachable."""
import hashlib
import random

from . import config

BANK = [
    # ─── VOCABULARY ──────────────────────────────────────────────────────────
    {"category": "vocabulary", "type": "mc",
     "question": "The explorer was RELUCTANT to enter the dark cave. What does 'reluctant' mean?",
     "passage": None,
     "options": ["A. Excited", "B. Unwilling or hesitant", "C. Prepared", "D. Curious"],
     "answer": "B",
     "explanation": "'Reluctant' means hesitant or unwilling — the explorer wasn't sure they wanted to go in."},
    {"category": "vocabulary", "type": "mc",
     "question": "Which sentence uses 'abundant' correctly?",
     "passage": None,
     "options": ["A. The garden had abundant tomatoes this summer.",
                 "B. She felt abundant after eating a big meal.",
                 "C. The abundant was very tall and strong.",
                 "D. He was abundant at the party last night."],
     "answer": "A",
     "explanation": "'Abundant' means existing in large amounts — tomatoes growing in large numbers is correct."},
    {"category": "vocabulary", "type": "mc",
     "question": "The scientist made a HYPOTHESIS before starting the experiment. What is a 'hypothesis'?",
     "passage": None,
     "options": ["A. A final answer", "B. An educated guess or prediction",
                 "C. A type of microscope", "D. A written report"],
     "answer": "B",
     "explanation": "A hypothesis is a prediction you can test — it's your best guess before you have proof."},
    {"category": "vocabulary", "type": "mc",
     "question": "The ELABORATE costume took three weeks to make. What does 'elaborate' mean?",
     "passage": None,
     "options": ["A. Simple and plain", "B. Detailed and complex",
                 "C. Cheap and easy", "D. Dark and scary"],
     "answer": "B",
     "explanation": "'Elaborate' means having many details or parts — something that took a lot of effort to create."},
    {"category": "vocabulary", "type": "mc",
     "question": "After the argument, the friends tried to find a COMPROMISE. What is a 'compromise'?",
     "passage": None,
     "options": ["A. A way to win the argument",
                 "B. An agreement where each side gives up something",
                 "C. A reason to stop being friends",
                 "D. A loud disagreement"],
     "answer": "B",
     "explanation": "A compromise means meeting in the middle — both sides adjust so everyone can agree."},
    {"category": "vocabulary", "type": "mc",
     "question": "The ruins were ANCIENT — built thousands of years ago. What does 'ancient' mean?",
     "passage": None,
     "options": ["A. Brand new", "B. Very old",
                 "C. Extremely large", "D. Brightly colored"],
     "answer": "B",
     "explanation": "'Ancient' means extremely old, usually referring to something from thousands of years in the past."},
    {"category": "vocabulary", "type": "mc",
     "question": "The video went VIRAL — millions of people saw it in one day. What does 'viral' mean here?",
     "passage": None,
     "options": ["A. It made people sick", "B. It was deleted quickly",
                 "C. It spread rapidly to many people", "D. It was very long"],
     "answer": "C",
     "explanation": "When something goes 'viral' online, it spreads quickly from person to person like a chain reaction."},
    {"category": "vocabulary", "type": "mc",
     "question": "The teacher asked students to COLLABORATE on the group project. What does 'collaborate' mean?",
     "passage": None,
     "options": ["A. Work alone", "B. Argue about ideas",
                 "C. Work together", "D. Copy someone else's work"],
     "answer": "C",
     "explanation": "'Collaborate' means to work together with others toward a shared goal."},
    {"category": "vocabulary", "type": "mc",
     "question": "The magician created an ILLUSION that fooled the entire audience. What is an 'illusion'?",
     "passage": None,
     "options": ["A. A true story", "B. Something that tricks your senses",
                 "C. A loud noise", "D. A bright light"],
     "answer": "B",
     "explanation": "An illusion is something that appears real but isn't — it tricks your eyes or mind."},
    {"category": "vocabulary", "type": "mc",
     "question": "The FRIGID wind made everyone shiver. What does 'frigid' mean?",
     "passage": None,
     "options": ["A. Gentle and warm", "B. Extremely cold",
                 "C. Fast-moving", "D. Loud and howling"],
     "answer": "B",
     "explanation": "'Frigid' means intensely cold — cold enough to make you shiver immediately."},
    {"category": "vocabulary", "type": "mc",
     "question": "She showed great PERSEVERANCE by practicing piano every day for a year. What is 'perseverance'?",
     "passage": None,
     "options": ["A. Talent without effort", "B. Giving up when things are hard",
                 "C. Continuing despite difficulty", "D. Being the best at something"],
     "answer": "C",
     "explanation": "'Perseverance' means keeping at something even when it's tough — sticking with it no matter what."},
    {"category": "vocabulary", "type": "mc",
     "question": "The AGILE cat leaped from branch to branch without slipping. What does 'agile' mean?",
     "passage": None,
     "options": ["A. Heavy and slow", "B. Quick and graceful in movement",
                 "C. Very loud", "D. Extremely lazy"],
     "answer": "B",
     "explanation": "'Agile' means able to move quickly and easily — like a cat jumping through trees."},
    {"category": "vocabulary", "type": "mc",
     "question": "The DENSE fog made it impossible to see more than a few feet ahead. What does 'dense' mean here?",
     "passage": None,
     "options": ["A. Thin and see-through", "B. Thick and closely packed",
                 "C. Colorful", "D. Moving quickly"],
     "answer": "B",
     "explanation": "'Dense' means thick and tightly packed together — dense fog is so thick you can barely see through it."},
    {"category": "vocabulary", "type": "mc",
     "question": "The comedian's WITTY response made the whole audience laugh. What does 'witty' mean?",
     "passage": None,
     "options": ["A. Rude and mean", "B. Clever and funny",
                 "C. Quiet and shy", "D. Long and boring"],
     "answer": "B",
     "explanation": "'Witty' means clever and humorous — a quick, smart response that makes people laugh."},

    # ─── GRAMMAR ─────────────────────────────────────────────────────────────
    {"category": "grammar", "type": "mc",
     "question": "Which sentence is punctuated correctly?",
     "passage": None,
     "options": ["A. The dog barked, and the cat ran away.",
                 "B. The dog barked and, the cat ran away.",
                 "C. The dog barked, and, the cat ran away.",
                 "D. The dog, barked and the cat ran away."],
     "answer": "A",
     "explanation": "When joining two complete sentences with 'and', the comma goes before the conjunction."},
    {"category": "grammar", "type": "mc",
     "question": "Identify the subject of this sentence: 'After the storm, the soccer field flooded completely.'",
     "passage": None,
     "options": ["A. storm", "B. the soccer field", "C. flooded", "D. completely"],
     "answer": "B",
     "explanation": "Ask 'what flooded?' The soccer field — that's the subject."},
    {"category": "grammar", "type": "mc",
     "question": "Which sentence uses the correct form of the verb?",
     "passage": None,
     "options": ["A. The group of players are running late.",
                 "B. The group of players is running late.",
                 "C. The group of players were runs late.",
                 "D. The group of players be running late."],
     "answer": "B",
     "explanation": "'Group' is the subject and it's singular — so 'is' is the correct verb form."},
    {"category": "grammar", "type": "mc",
     "question": "Which sentence correctly uses a semicolon?",
     "passage": None,
     "options": ["A. I love pizza; it's my favorite food.",
                 "B. I love; pizza it's my favorite food.",
                 "C. I love pizza it's; my favorite food.",
                 "D. I; love pizza it's my favorite food."],
     "answer": "A",
     "explanation": "A semicolon joins two complete sentences that are closely related — each side must be a full thought."},
    {"category": "grammar", "type": "mc",
     "question": "Which word is an adverb in this sentence: 'She quickly finished her homework.'",
     "passage": None,
     "options": ["A. She", "B. quickly", "C. finished", "D. homework"],
     "answer": "B",
     "explanation": "'Quickly' describes HOW she finished — adverbs describe verbs and often end in '-ly'."},
    {"category": "grammar", "type": "mc",
     "question": "Which sentence has a correct possessive?",
     "passage": None,
     "options": ["A. The dogs bone was buried in the yard.",
                 "B. The dog's bone was buried in the yard.",
                 "C. The dogs' bone was buried in the yard.",
                 "D. The dog bone's was buried in the yard."],
     "answer": "B",
     "explanation": "One dog owns the bone, so the apostrophe goes before the 's': dog's."},
    {"category": "grammar", "type": "mc",
     "question": "Which sentence uses 'who' and 'whom' correctly?",
     "passage": None,
     "options": ["A. Who did you give the book to?",
                 "B. Whom is coming to the party?",
                 "C. To whom did you give the book?",
                 "D. Whom is your best friend?"],
     "answer": "C",
     "explanation": "'Whom' is used when it's receiving the action (the object). 'To whom' — the book was given TO that person."},
    {"category": "grammar", "type": "mc",
     "question": "Which sentence has correct subject-verb agreement?",
     "passage": None,
     "options": ["A. Neither the cats nor the dog were hungry.",
                 "B. Neither the cats nor the dog was hungry.",
                 "C. Neither the cats nor the dog are hungry.",
                 "D. Neither the cats nor the dog have been hungry."],
     "answer": "B",
     "explanation": "With 'neither...nor', the verb matches the nearest subject — 'dog' is singular, so use 'was'."},
    {"category": "grammar", "type": "mc",
     "question": "What type of sentence is this: 'Although it rained, we still played outside.'",
     "passage": None,
     "options": ["A. Simple", "B. Compound", "C. Complex", "D. Fragment"],
     "answer": "C",
     "explanation": "A complex sentence has an independent clause ('we still played outside') joined by a dependent clause ('Although it rained')."},
    {"category": "grammar", "type": "mc",
     "question": "Which sentence uses parallel structure correctly?",
     "passage": None,
     "options": ["A. She likes swimming, biking, and to run.",
                 "B. She likes swimming, biking, and running.",
                 "C. She likes to swim, biking, and running.",
                 "D. She likes swimming, to bike, and running."],
     "answer": "B",
     "explanation": "Parallel structure means using the same word form for a list — all three end in '-ing' here."},
    {"category": "grammar", "type": "mc",
     "question": "Which sentence correctly uses a comma with an introductory phrase?",
     "passage": None,
     "options": ["A. Before the game started the players stretched.",
                 "B. Before the game started, the players stretched.",
                 "C. Before, the game started the players stretched.",
                 "D. Before the game, started the players stretched."],
     "answer": "B",
     "explanation": "After an introductory phrase ('Before the game started'), use a comma before the main clause."},
    {"category": "grammar", "type": "mc",
     "question": "Which word is a conjunction in this sentence: 'I wanted to play, but it was raining.'",
     "passage": None,
     "options": ["A. wanted", "B. play", "C. but", "D. raining"],
     "answer": "C",
     "explanation": "'But' is a conjunction — it connects two ideas that contrast with each other."},
    {"category": "grammar", "type": "mc",
     "question": "Which sentence avoids a dangling modifier?",
     "passage": None,
     "options": ["A. Running down the street, the house came into view.",
                 "B. Running down the street, I saw the house come into view.",
                 "C. Running down the street, it was getting dark.",
                 "D. Running down the street, the rain started."],
     "answer": "B",
     "explanation": "The modifier 'Running down the street' must describe the subject — only 'I' can actually run."},
    {"category": "grammar", "type": "mc",
     "question": "Which is a complete sentence (not a fragment)?",
     "passage": None,
     "options": ["A. Because the movie was too long.",
                 "B. Running fast through the park.",
                 "C. The movie was too long for us.",
                 "D. Although she tried her best."],
     "answer": "C",
     "explanation": "A complete sentence needs a subject and verb that express a complete thought. The others are fragments that leave you hanging."},

    # ─── READING ─────────────────────────────────────────────────────────────
    {"category": "reading", "type": "mc",
     "question": "What is the main idea of the passage?",
     "passage": "Octopuses are escape artists of the ocean. They can squeeze through any opening larger than their beak. Aquarium workers have found them in filter pipes, other tanks, and even on the floor heading toward the sea. Some aquariums now use special lids just for octopuses.",
     "options": ["A. Octopuses have beaks.", "B. Aquariums use special lids.",
                 "C. Octopuses are remarkably good at escaping.", "D. Octopuses live in the ocean."],
     "answer": "C",
     "explanation": "Every sentence supports one big idea: octopuses escape from almost anything."},
    {"category": "reading", "type": "mc",
     "question": "Based on the passage, why did Maya keep checking her watch?",
     "passage": "Maya kept checking her watch as she waited at the bus stop. Her science fair project — a volcano that actually smoked — sat carefully balanced on her lap. Judging started at nine o'clock sharp, and the bus was already six minutes late.",
     "options": ["A. She didn't like waiting for the bus.",
                 "B. She was nervous about being late to science fair judging because the bus was delayed.",
                 "C. She wanted to know what time it was.",
                 "D. The volcano project needed to be done at a certain time."],
     "answer": "B",
     "explanation": "The passage shows the bus is late, judging starts at nine sharp, and her project is with her — she's worried about missing the judging deadline."},
    {"category": "reading", "type": "mc",
     "question": "What can you infer about the character from this passage?",
     "passage": "Jordan checked his gear one more time: helmet, knee pads, elbow pads. He stared down the half-pipe, gripping his skateboard so tightly his knuckles turned white. The other kids made it look easy. He took a deep breath and whispered, 'You've practiced this a hundred times.'",
     "options": ["A. Jordan is an expert skateboarder.",
                 "B. Jordan is nervous but determined.",
                 "C. Jordan doesn't want to skateboard.",
                 "D. Jordan has never practiced before."],
     "answer": "B",
     "explanation": "White knuckles and a deep breath show nerves, but his self-talk shows he's pushing through — nervous but determined."},
    {"category": "reading", "type": "mc",
     "question": "What is the author's purpose in this passage?",
     "passage": "Honeybees communicate through dance. A 'waggle dance' tells other bees exactly where flowers are — the angle shows direction relative to the sun, and the length of the waggle tells distance. One tiny bee is basically drawing a map for thousands of others.",
     "options": ["A. To persuade readers to protect bees.",
                 "B. To entertain readers with a funny story.",
                 "C. To inform readers about how bees communicate.",
                 "D. To compare bees to other insects."],
     "answer": "C",
     "explanation": "The passage explains facts about how bees share information — the purpose is to inform."},
    {"category": "reading", "type": "mc",
     "question": "What does the word 'staggering' mean in this passage?",
     "passage": "The Amazon rainforest contains a staggering number of species. Scientists estimate over 400 billion individual trees from 16,000 different species live there. Every year, researchers discover dozens of species that are completely new to science.",
     "options": ["A. A small number", "B. An exact number",
                 "C. An overwhelmingly large number", "D. A decreasing number"],
     "answer": "C",
     "explanation": "Context clues like '400 billion' and '16,000 species' show 'staggering' means an amazingly large amount."},
    {"category": "reading", "type": "mc",
     "question": "Which statement is an OPINION, not a fact from the passage?",
     "passage": "The International Space Station orbits Earth about 16 times per day at 17,500 miles per hour. Six astronauts typically live aboard, conducting experiments in the weightless environment. It's the most amazing engineering achievement in human history.",
     "options": ["A. The ISS orbits Earth about 16 times per day.",
                 "B. Six astronauts typically live aboard.",
                 "C. It travels at 17,500 miles per hour.",
                 "D. It's the most amazing engineering achievement in human history."],
     "answer": "D",
     "explanation": "'Most amazing' is a judgment — that's an opinion. The other statements can be verified with facts."},
    {"category": "reading", "type": "mc",
     "question": "What is the most likely reason the author included the last sentence?",
     "passage": "In 1969, the Apollo 11 crew landed on the Moon with a computer less powerful than a modern calculator. The navigation computer had just 74 kilobytes of memory. Today, a basic smartphone has over a million times more computing power than what guided astronauts to the Moon and back.",
     "options": ["A. To explain how calculators work.",
                 "B. To show how much technology has improved since 1969.",
                 "C. To argue that smartphones are better than space travel.",
                 "D. To prove the Moon landing was difficult."],
     "answer": "B",
     "explanation": "Comparing the old computer to today's smartphone highlights the massive leap in technology over time."},
    {"category": "reading", "type": "mc",
     "question": "Based on the passage, what will most likely happen next?",
     "passage": "Lena lined up the dominos carefully across the kitchen table, around the fruit bowl, and down the table leg to the floor. The chain continued across the living room to the front door. She had spent two hours on the setup. Now she positioned her finger behind the very first domino and grinned.",
     "options": ["A. She will carefully put the dominos away.",
                 "B. She will knock over the first domino to start a chain reaction.",
                 "C. She will add more dominos to the chain.",
                 "D. She will call a friend to come see them standing."],
     "answer": "B",
     "explanation": "She's positioned to push the first one and is grinning — the setup is complete and she's about to start the chain."},
    {"category": "reading", "type": "mc",
     "question": "What is the text structure of this passage?",
     "passage": "Many students struggle with test anxiety. Their hearts race, their palms sweat, and they forget material they studied. However, there are effective solutions. Deep breathing before a test calms the nervous system. Studying in short sessions over several days builds stronger memory than cramming the night before.",
     "options": ["A. Cause and effect", "B. Chronological order",
                 "C. Problem and solution", "D. Compare and contrast"],
     "answer": "C",
     "explanation": "The passage first describes the problem (test anxiety symptoms) then offers solutions (breathing, spaced studying)."},
    {"category": "reading", "type": "mc",
     "question": "What can you conclude about the narrator?",
     "passage": "I'd mapped every constellation visible from my backyard by age ten. My walls were covered in star charts, and my allowance went straight to telescope upgrades. So when Ms. Rivera announced the astronomy club field trip to the observatory, I almost fell out of my chair.",
     "options": ["A. The narrator is bored by school.",
                 "B. The narrator is deeply passionate about astronomy.",
                 "C. The narrator doesn't like spending money.",
                 "D. The narrator just recently became interested in stars."],
     "answer": "B",
     "explanation": "Mapping constellations by age ten, covering walls with charts, spending all their allowance — this is someone deeply passionate."},
    {"category": "reading", "type": "mc",
     "question": "Which detail from the passage BEST supports the idea that the dog is loyal?",
     "passage": "Every morning at 6:45, Bruno sits by the front door and waits. When Alex grabs his backpack, Bruno follows him to the bus stop and watches until the bus disappears around the corner. Every afternoon at 3:15, Bruno returns to the same spot and waits again, tail wagging the moment the yellow bus reappears.",
     "options": ["A. Bruno sits by the front door.",
                 "B. Alex grabs his backpack.",
                 "C. Bruno returns every afternoon at 3:15 to the same spot.",
                 "D. The bus disappears around the corner."],
     "answer": "C",
     "explanation": "Returning to the exact same spot every single day shows devoted loyalty — Bruno never forgets or gives up waiting."},
    {"category": "reading", "type": "mc",
     "question": "What tone does the author use in this passage?",
     "passage": "Oh sure, homework is GREAT. Nothing I love more than spending my Friday night calculating the area of triangles instead of, you know, having a life. Thanks so much for that, Mrs. Patterson.",
     "options": ["A. Sincere and grateful", "B. Sad and depressed",
                 "C. Sarcastic and frustrated", "D. Confused and curious"],
     "answer": "C",
     "explanation": "The all-caps 'GREAT' and 'Thanks so much' are clearly the opposite of what the narrator means — that's sarcasm mixed with frustration."},
    {"category": "reading", "type": "mc",
     "question": "What is the theme of this passage?",
     "passage": "Mia's painting looked nothing like the mountain she was trying to capture. The colors were wrong, the proportions off. She almost crumpled it up. But her art teacher said, 'Compare it to your painting from September.' Mia looked — and realized she'd improved more than she thought. She picked up her brush again.",
     "options": ["A. Art is only for talented people.",
                 "B. Teachers always know best.",
                 "C. Progress matters more than perfection.",
                 "D. Mountains are hard to paint."],
     "answer": "C",
     "explanation": "Mia almost quit but seeing her growth motivated her to continue — the theme is that progress (not perfection) is what counts."},

    # ─── FIGURATIVE LANGUAGE ─────────────────────────────────────────────────
    {"category": "figurative_language", "type": "mc",
     "question": "'The classroom was a zoo before the teacher arrived.' This is an example of:",
     "passage": None,
     "options": ["A. Simile", "B. Metaphor", "C. Personification", "D. Onomatopoeia"],
     "answer": "B",
     "explanation": "It compares the classroom to a zoo WITHOUT using 'like' or 'as' — that's a metaphor."},
    {"category": "figurative_language", "type": "mc",
     "question": "Which sentence is a simile describing how fast a cheetah runs?",
     "passage": None,
     "options": ["A. The cheetah is a lightning bolt.",
                 "B. The cheetah ran like lightning across the plain.",
                 "C. The swift cheetah zoomed by.",
                 "D. The cheetah's speed was incredible."],
     "answer": "B",
     "explanation": "A simile uses 'like' or 'as' to compare two things — this one compares the cheetah to lightning."},
    {"category": "figurative_language", "type": "mc",
     "question": "'The wind whispered through the trees.' This is an example of:",
     "passage": None,
     "options": ["A. Simile", "B. Alliteration", "C. Personification", "D. Hyperbole"],
     "answer": "C",
     "explanation": "Personification gives human traits to non-human things — wind can't actually whisper, only people can."},
    {"category": "figurative_language", "type": "mc",
     "question": "'I've told you a million times to clean your room!' This is an example of:",
     "passage": None,
     "options": ["A. Metaphor", "B. Simile", "C. Personification", "D. Hyperbole"],
     "answer": "D",
     "explanation": "Hyperbole is extreme exaggeration for effect — nobody has actually said something a million times."},
    {"category": "figurative_language", "type": "mc",
     "question": "Which line contains alliteration?",
     "passage": None,
     "options": ["A. The cat sat on the mat.",
                 "B. Peter Piper picked a peck of pickled peppers.",
                 "C. She sells by the seashore.",
                 "D. Both B and C."],
     "answer": "D",
     "explanation": "Alliteration is the repetition of beginning consonant sounds — 'P' repeats in B and 'S' repeats in C."},
    {"category": "figurative_language", "type": "mc",
     "question": "'The news hit her like a ton of bricks.' This is an example of:",
     "passage": None,
     "options": ["A. Metaphor", "B. Simile", "C. Personification", "D. Idiom"],
     "answer": "B",
     "explanation": "It uses 'like' to compare the impact of news to being hit by bricks — that's a simile."},
    {"category": "figurative_language", "type": "mc",
     "question": "'Time is money.' This is an example of:",
     "passage": None,
     "options": ["A. Simile", "B. Metaphor", "C. Onomatopoeia", "D. Alliteration"],
     "answer": "B",
     "explanation": "It says time IS money (not 'like money') — directly equating two unlike things without 'like' or 'as' is a metaphor."},
    {"category": "figurative_language", "type": "mc",
     "question": "'The thunder BOOMED and the rain went SPLAT against the window.' The capitalized words are examples of:",
     "passage": None,
     "options": ["A. Simile", "B. Hyperbole", "C. Onomatopoeia", "D. Metaphor"],
     "answer": "C",
     "explanation": "Onomatopoeia is when a word sounds like what it describes — 'boomed' and 'splat' sound like the noises they name."},
    {"category": "figurative_language", "type": "mc",
     "question": "'The old car coughed and sputtered before finally starting.' This is an example of:",
     "passage": None,
     "options": ["A. Personification", "B. Simile", "C. Hyperbole", "D. Alliteration"],
     "answer": "A",
     "explanation": "Cars can't actually cough — giving a machine human-like actions is personification."},
    {"category": "figurative_language", "type": "mc",
     "question": "What does the idiom 'break the ice' mean?",
     "passage": None,
     "options": ["A. To literally break frozen water",
                 "B. To make people feel more comfortable in an awkward situation",
                 "C. To start a fight",
                 "D. To solve a difficult problem"],
     "answer": "B",
     "explanation": "'Break the ice' means to ease tension or start conversation in an uncomfortable social situation."},
    {"category": "figurative_language", "type": "mc",
     "question": "'Her smile was as bright as the sun.' This is an example of:",
     "passage": None,
     "options": ["A. Metaphor", "B. Simile", "C. Personification", "D. Hyperbole"],
     "answer": "B",
     "explanation": "It uses 'as...as' to compare her smile to the sun — comparing with 'as' makes it a simile."},
    {"category": "figurative_language", "type": "mc",
     "question": "'Life is a roller coaster.' This is an example of:",
     "passage": None,
     "options": ["A. Simile", "B. Hyperbole", "C. Metaphor", "D. Personification"],
     "answer": "C",
     "explanation": "It directly says life IS a roller coaster without using 'like' or 'as' — that makes it a metaphor."},
    {"category": "figurative_language", "type": "mc",
     "question": "'The backpack weighed a thousand pounds.' This is an example of:",
     "passage": None,
     "options": ["A. Simile", "B. Personification", "C. Metaphor", "D. Hyperbole"],
     "answer": "D",
     "explanation": "No backpack actually weighs 1,000 pounds — this is extreme exaggeration (hyperbole) to show how heavy it felt."},

    # ─── WRITING MECHANICS ───────────────────────────────────────────────────
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which word correctly completes the sentence: 'The team celebrated ___ victory.'",
     "passage": None,
     "options": ["A. they're", "B. their", "C. there", "D. theyre"],
     "answer": "B",
     "explanation": "'Their' shows ownership — the victory belongs to the team."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which sentence uses 'its' and 'it's' correctly?",
     "passage": None,
     "options": ["A. Its a beautiful day outside.",
                 "B. The dog wagged it's tail.",
                 "C. It's going to rain, so bring its umbrella.",
                 "D. It's a shame the bird hurt its wing."],
     "answer": "D",
     "explanation": "'It's' = 'it is' (a shame). 'Its' = belonging to it (the bird's wing). No apostrophe for possession with 'its'."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which sentence uses a colon correctly?",
     "passage": None,
     "options": ["A. I need: eggs, milk, and bread.",
                 "B. I need three things: eggs, milk, and bread.",
                 "C. I need three things: and they are eggs, milk, bread.",
                 "D. I: need eggs, milk, and bread."],
     "answer": "B",
     "explanation": "A colon comes after a complete sentence that introduces a list — 'I need three things' is complete on its own."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which sentence correctly uses quotation marks?",
     "passage": None,
     "options": ["A. She said I'm leaving now.",
                 "B. She said, \"I'm leaving now.\"",
                 "C. \"She said, I'm leaving now.\"",
                 "D. She said, \"I'm leaving now\"."],
     "answer": "B",
     "explanation": "Quotation marks go around the exact words spoken, with the period INSIDE the closing quotation mark."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which word correctly completes the sentence: 'The book had a big ___ on the story.'",
     "passage": None,
     "options": ["A. affect", "B. effect", "C. affecte", "D. efect"],
     "answer": "B",
     "explanation": "'Effect' is usually a noun (the result of something). 'Affect' is usually a verb (to influence something)."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which sentence has correct capitalization?",
     "passage": None,
     "options": ["A. We visited the grand canyon last Summer.",
                 "B. We visited the Grand canyon last summer.",
                 "C. We visited the Grand Canyon last summer.",
                 "D. We Visited The Grand Canyon Last Summer."],
     "answer": "C",
     "explanation": "'Grand Canyon' is a proper noun (specific place name) so both words are capitalized. Seasons aren't capitalized."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which is the correct way to write a contraction of 'could not'?",
     "passage": None,
     "options": ["A. could'nt", "B. couldnt", "C. couldn't", "D. could not'"],
     "answer": "C",
     "explanation": "The apostrophe replaces the missing letter 'o' from 'not' — could + n't = couldn't."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which sentence uses commas correctly in a list?",
     "passage": None,
     "options": ["A. I packed a tent sleeping bag, and flashlight.",
                 "B. I packed a tent, sleeping bag and flashlight.",
                 "C. I packed a tent, sleeping bag, and flashlight.",
                 "D. I packed, a tent, sleeping bag, and flashlight."],
     "answer": "C",
     "explanation": "In a list of three or more items, commas separate each item. The comma before 'and' (Oxford comma) makes it clearest."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which word correctly completes: 'She did ___ than everyone expected.'",
     "passage": None,
     "options": ["A. good", "B. better", "C. more better", "D. bestest"],
     "answer": "B",
     "explanation": "'Better' is the comparative form of 'good' — use it when comparing. Never double up ('more better') or invent forms ('bestest')."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which sentence correctly uses an apostrophe?",
     "passage": None,
     "options": ["A. The girl's are playing outside.",
                 "B. The girls' locker room needs painting.",
                 "C. The girl's playing outside.",
                 "D. The girls's locker room needs painting."],
     "answer": "B",
     "explanation": "Multiple girls share one locker room — for plural possessive, the apostrophe goes after the 's': girls'."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which transition word best completes this sentence: 'I studied hard for the test. ___, I got an A.'",
     "passage": None,
     "options": ["A. However,", "B. Although,", "C. As a result,", "D. On the other hand,"],
     "answer": "C",
     "explanation": "The A is a RESULT of studying hard — 'As a result' shows cause and effect."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which sentence uses 'then' and 'than' correctly?",
     "passage": None,
     "options": ["A. She is taller then her brother.",
                 "B. First mix the batter, than bake it.",
                 "C. He is faster than me, then he slowed down.",
                 "D. She is taller than her brother."],
     "answer": "D",
     "explanation": "'Than' is for comparisons (taller than). 'Then' is for time/sequence (first this, then that)."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which sentence avoids a run-on?",
     "passage": None,
     "options": ["A. I love soccer I play every day.",
                 "B. I love soccer, I play every day.",
                 "C. I love soccer, so I play every day.",
                 "D. I love soccer I, play every day."],
     "answer": "C",
     "explanation": "Two complete thoughts need a conjunction with the comma ('so'). Without it, you get a run-on or comma splice."},

    # ─── MATH CHALLENGE ──────────────────────────────────────────────────────
    {"category": "math_challenge", "type": "mc",
     "question": "A game costs $48. It goes on sale for 25% off, then you have a coupon for $5 off the sale price. What do you pay?",
     "passage": None,
     "options": ["A. $31", "B. $36", "C. $38", "D. $43"],
     "answer": "A",
     "explanation": "25% of 48 is 12, so the sale price is $36. Minus the $5 coupon = $31."},
    {"category": "math_challenge", "type": "mc",
     "question": "Two hoses fill a pool. Hose A fills it alone in 6 hours; Hose B in 3 hours. Together, how long?",
     "passage": None,
     "options": ["A. 4.5 hours", "B. 2 hours", "C. 3 hours", "D. 1.5 hours"],
     "answer": "B",
     "explanation": "Per hour: A fills 1/6, B fills 1/3. Together 1/6 + 2/6 = 3/6 = half the pool per hour → 2 hours."},
    {"category": "math_challenge", "type": "mc",
     "question": "A recipe uses 3 cups of flour for every 2 cups of sugar. You use 9 cups of flour. How much sugar?",
     "passage": None,
     "options": ["A. 4 cups", "B. 5 cups", "C. 6 cups", "D. 7 cups"],
     "answer": "C",
     "explanation": "9 flour is 3× the recipe (3→9), so sugar is also 3×: 2→6 cups."},
    {"category": "math_challenge", "type": "mc",
     "question": "A train travels at 60 mph. A car leaves the same station 1 hour later at 80 mph. How long until the car catches the train?",
     "passage": None,
     "options": ["A. 2 hours", "B. 3 hours", "C. 4 hours", "D. 5 hours"],
     "answer": "B",
     "explanation": "After 1 hour the train is 60 miles ahead. The car gains 20 mph (80−60). 60 ÷ 20 = 3 hours to close the gap."},
    {"category": "math_challenge", "type": "mc",
     "question": "A store marks up shoes by 40%, then puts them on sale for 25% off. The original cost was $50. What's the sale price?",
     "passage": None,
     "options": ["A. $45", "B. $50", "C. $52.50", "D. $57.50"],
     "answer": "C",
     "explanation": "40% markup: $50 × 1.4 = $70. Then 25% off: $70 × 0.75 = $52.50."},
    {"category": "math_challenge", "type": "mc",
     "question": "If 3x + 7 = 22, what is x?",
     "passage": None,
     "options": ["A. 3", "B. 5", "C. 7", "D. 9"],
     "answer": "B",
     "explanation": "Subtract 7 from both sides: 3x = 15. Divide by 3: x = 5."},
    {"category": "math_challenge", "type": "mc",
     "question": "A triangle has angles measuring 45° and 90°. What is the third angle?",
     "passage": None,
     "options": ["A. 35°", "B. 45°", "C. 55°", "D. 65°"],
     "answer": "B",
     "explanation": "Triangle angles sum to 180°. 180 − 45 − 90 = 45°."},
    {"category": "math_challenge", "type": "mc",
     "question": "A rectangular garden is 12 feet long and 8 feet wide. How much fencing do you need to go all the way around?",
     "passage": None,
     "options": ["A. 20 feet", "B. 32 feet", "C. 40 feet", "D. 96 feet"],
     "answer": "C",
     "explanation": "Perimeter = 2 × (length + width) = 2 × (12 + 8) = 2 × 20 = 40 feet."},
    {"category": "math_challenge", "type": "mc",
     "question": "You flip a fair coin 3 times. What's the probability of getting heads all 3 times?",
     "passage": None,
     "options": ["A. 1/2", "B. 1/4", "C. 1/6", "D. 1/8"],
     "answer": "D",
     "explanation": "Each flip has 1/2 chance of heads. Three flips: 1/2 × 1/2 × 1/2 = 1/8."},
    {"category": "math_challenge", "type": "mc",
     "question": "A pizza is cut into 8 equal slices. You eat 3 slices and your friend eats 2. What fraction of the pizza is LEFT?",
     "passage": None,
     "options": ["A. 5/8", "B. 3/8", "C. 1/2", "D. 1/4"],
     "answer": "B",
     "explanation": "You ate 3/8, friend ate 2/8. Total eaten: 5/8. Left: 8/8 − 5/8 = 3/8."},
    {"category": "math_challenge", "type": "mc",
     "question": "A bike costs $240. You save $18 per week. Your friend saves $22 per week but started 2 weeks later. Who buys the bike first?",
     "passage": None,
     "options": ["A. You, by 1 week", "B. Your friend, by 1 week",
                 "C. You both buy it the same week", "D. You, by 2 weeks"],
     "answer": "B",
     "explanation": "You need 240 ÷ 18 = 14 weeks (week 13 only gets you to $234). Friend needs 240 ÷ 22 = 11 weeks ($242), plus the 2-week late start = done by week 13. Friend beats you by 1 week."},
    {"category": "math_challenge", "type": "mc",
     "question": "What is 15% of 80?",
     "passage": None,
     "options": ["A. 10", "B. 12", "C. 15", "D. 18"],
     "answer": "B",
     "explanation": "10% of 80 is 8. 5% of 80 is 4. Add them: 8 + 4 = 12."},
    {"category": "math_challenge", "type": "mc",
     "question": "A box holds 24 crayons. You need enough for 150 students, 1 box each. Crayons come in packs of 6 boxes. How many packs do you need to buy?",
     "passage": None,
     "options": ["A. 24 packs", "B. 25 packs", "C. 26 packs", "D. 150 packs"],
     "answer": "B",
     "explanation": "150 students need 150 boxes. Each pack has 6 boxes. 150 ÷ 6 = 25 packs exactly."},
    {"category": "math_challenge", "type": "mc",
     "question": "An elevator can hold 1,200 pounds. Adults average 180 lbs and children average 70 lbs. Can 5 adults and 3 children ride together?",
     "passage": None,
     "options": ["A. Yes, with 90 lbs to spare", "B. Yes, with 110 lbs to spare",
                 "C. No, they're 10 lbs over", "D. No, they're 90 lbs over"],
     "answer": "A",
     "explanation": "5 adults: 5 × 180 = 900. 3 children: 3 × 70 = 210. Total: 1,110. Space left: 1,200 − 1,110 = 90 lbs."},
    {"category": "math_challenge", "type": "mc",
     "question": "A square has an area of 64 square inches. What is the length of one side?",
     "passage": None,
     "options": ["A. 4 inches", "B. 8 inches", "C. 16 inches", "D. 32 inches"],
     "answer": "B",
     "explanation": "Area of a square = side × side. What times itself = 64? 8 × 8 = 64."},
    {"category": "math_challenge", "type": "mc",
     "question": "You score 85, 92, and 78 on three tests. What score do you need on the fourth test to average exactly 85?",
     "passage": None,
     "options": ["A. 83", "B. 85", "C. 87", "D. 90"],
     "answer": "B",
     "explanation": "Need total of 85 × 4 = 340. Current total: 85 + 92 + 78 = 255. Need: 340 − 255 = 85."},
    {"category": "math_challenge", "type": "mc",
     "question": "A map scale is 1 inch = 25 miles. Two cities are 3.5 inches apart on the map. How far apart are they in real life?",
     "passage": None,
     "options": ["A. 75 miles", "B. 82.5 miles", "C. 87.5 miles", "D. 100 miles"],
     "answer": "C",
     "explanation": "3.5 inches × 25 miles per inch = 87.5 miles."},
    {"category": "math_challenge", "type": "mc",
     "question": "A shirt is $35. Sales tax is 8%. What's the total cost?",
     "passage": None,
     "options": ["A. $36.80", "B. $37.40", "C. $37.80", "D. $38.50"],
     "answer": "C",
     "explanation": "8% of $35: 0.08 × 35 = $2.80. Total: $35 + $2.80 = $37.80."},
    {"category": "math_challenge", "type": "mc",
     "question": "A bus leaves at 7:45 AM and arrives at 10:20 AM. How long is the trip?",
     "passage": None,
     "options": ["A. 2 hours 25 minutes", "B. 2 hours 35 minutes",
                 "C. 2 hours 45 minutes", "D. 3 hours 25 minutes"],
     "answer": "B",
     "explanation": "From 7:45 to 10:45 would be 3 hours, but it's only to 10:20 — that's 25 minutes less. 3h − 25min = 2h 35min."},
    {"category": "math_challenge", "type": "mc",
     "question": "You have 3/4 of a pizza. You eat 1/3 of what you have. How much of the WHOLE pizza did you eat?",
     "passage": None,
     "options": ["A. 1/4", "B. 1/3", "C. 1/2", "D. 5/12"],
     "answer": "A",
     "explanation": "1/3 of 3/4 = 1/3 × 3/4 = 3/12 = 1/4 of the whole pizza."},
    {"category": "math_challenge", "type": "mc",
     "question": "A car uses 1 gallon of gas every 28 miles. The tank holds 14 gallons. How far can you drive on a full tank?",
     "passage": None,
     "options": ["A. 352 miles", "B. 378 miles", "C. 392 miles", "D. 420 miles"],
     "answer": "C",
     "explanation": "14 gallons × 28 miles per gallon = 392 miles."},
    {"category": "math_challenge", "type": "mc",
     "question": "Three friends split a $45 bill equally, but one leaves a $6 tip for the whole table. How much does the tipper pay total?",
     "passage": None,
     "options": ["A. $15", "B. $18", "C. $21", "D. $23"],
     "answer": "C",
     "explanation": "Equal share: $45 ÷ 3 = $15. Plus the $6 tip: $15 + $6 = $21."},
    {"category": "math_challenge", "type": "mc",
     "question": "A rope is 5 feet long. You need pieces that are 8 inches each. How many complete pieces can you cut?",
     "passage": None,
     "options": ["A. 6 pieces", "B. 7 pieces", "C. 8 pieces", "D. 9 pieces"],
     "answer": "B",
     "explanation": "5 feet = 60 inches. 60 ÷ 8 = 7.5. You can only make complete pieces, so 7."},
    {"category": "math_challenge", "type": "mc",
     "question": "A store sells 3 pens for $2. How much do 15 pens cost?",
     "passage": None,
     "options": ["A. $8", "B. $10", "C. $12", "D. $15"],
     "answer": "B",
     "explanation": "15 pens ÷ 3 per group = 5 groups. 5 groups × $2 = $10."},
    {"category": "math_challenge", "type": "mc",
     "question": "You're 4.5 feet tall. Your shadow is 6 feet long. A tree's shadow is 24 feet. How tall is the tree?",
     "passage": None,
     "options": ["A. 16 feet", "B. 18 feet", "C. 20 feet", "D. 32 feet"],
     "answer": "B",
     "explanation": "Ratio: height/shadow = 4.5/6 = 0.75. Tree height: 24 × 0.75 = 18 feet."},
    {"category": "math_challenge", "type": "mc",
     "question": "A spinner has 5 equal sections: red, blue, green, yellow, and orange. What's the probability of NOT landing on red?",
     "passage": None,
     "options": ["A. 1/5", "B. 2/5", "C. 3/5", "D. 4/5"],
     "answer": "D",
     "explanation": "There are 4 sections that aren't red out of 5 total. Probability = 4/5."},
    {"category": "math_challenge", "type": "mc",
     "question": "A pool drains at 50 gallons per minute. It holds 3,000 gallons. You start draining at 2:00 PM. When is it empty?",
     "passage": None,
     "options": ["A. 2:30 PM", "B. 2:45 PM", "C. 3:00 PM", "D. 3:30 PM"],
     "answer": "C",
     "explanation": "3,000 ÷ 50 = 60 minutes = 1 hour. 2:00 PM + 1 hour = 3:00 PM."},
    {"category": "math_challenge", "type": "mc",
     "question": "A rectangular prism is 4 cm long, 3 cm wide, and 5 cm tall. What is its volume?",
     "passage": None,
     "options": ["A. 12 cm³", "B. 24 cm³", "C. 45 cm³", "D. 60 cm³"],
     "answer": "D",
     "explanation": "Volume = length × width × height = 4 × 3 × 5 = 60 cm³."},
]


def valid_question(q):
    """Shape check shared by the live-AI path and the pre-generated pool."""
    if not isinstance(q, dict):
        return False
    if q.get("category") not in config.CATEGORIES:
        return False
    if q.get("type") not in ("mc", "short"):
        return False
    if not q.get("question") or not q.get("answer"):
        return False
    if q["type"] == "mc" and len(q.get("options") or []) != 4:
        return False
    return True


def _qid(q):
    """Stable id for a bank question, derived from its text."""
    return hashlib.sha1(q["question"].encode("utf-8")).hexdigest()[:10]


# Give every bank question a stable id so progress can be tracked across sessions.
for _q in BANK:
    _q["id"] = _qid(_q)


def _order(pool, review):
    """Questions due for review (missed in a past session) come first, then
    fresh ones — each group shuffled so sessions still feel varied."""
    due = [q for q in pool if q["id"] in review]
    fresh = [q for q in pool if q["id"] not in review]
    random.shuffle(due)
    random.shuffle(fresh)
    return due + fresh


def _mc_from_numbers(correct, distractors):
    """Assemble a 4-option MC block from a correct number + wrong guesses,
    returning (options, answer_letter). Pads with near-misses if needed."""
    choices, k = [], 1
    for v in [correct, *distractors]:
        if v not in choices and v > 0:
            choices.append(v)
    while len(choices) < 4:
        if (correct + k) not in choices:
            choices.append(correct + k)
        k += 1
    choices = choices[:4]
    random.shuffle(choices)
    letters = ["A", "B", "C", "D"]
    options = [f"{letters[i]}. {choices[i]}" for i in range(4)]
    return options, letters[choices.index(correct)]


def personalized(prefs):
    """Build a couple of MC questions woven around the kid's favorites.

    Instant, offline, and deliberately EPHEMERAL — no stable id, and the math
    numbers are re-rolled every call, so these recur each session as fresh fun
    rather than being tracked/retired by the spaced-repetition system.
    """
    from . import config

    prefs = prefs or {}
    food = (prefs.get("food") or "pizza").strip()
    unit = config.FOOD_UNITS.get(food.lower(), config.DEFAULT_FOOD_UNIT)
    animal = (prefs.get("animal") or "cat").strip()

    per = random.choice([6, 7, 8, 9])
    servings = random.choice([2, 3, 4])
    eaten = random.choice([4, 5, 6, 7])
    total = per * servings
    left = total - eaten
    options, answer = _mc_from_numbers(left, [total, eaten, left + per])
    food_q = {
        "category": "math_challenge", "type": "mc",
        "question": (f"You get {servings} {food}, and each has {per} {unit}. "
                     f"You eat {eaten} {unit} in all. How many {unit} are left?"),
        "passage": None, "options": options, "answer": answer,
        "explanation": f"{servings} × {per} = {total} {unit} to start. {total} − {eaten} = {left} left.",
    }

    # Each passage is paired with an explanation that only cites cues actually
    # in THAT passage — so the "why" never references text the kid didn't see.
    passage, explanation = random.choice([
        ((f"A curious {animal} crept along the moonlit shore. Fireflies blinked near "
          f"an old lighthouse as waves whispered against the rocks. The {animal} had "
          f"never wandered so far from home, but tonight, adventure was too tempting to resist."),
         (f"The {animal} creeps out to explore and finds the adventure 'too tempting to "
          f"resist' — that shows curiosity and eagerness, not fear or boredom.")),
        ((f"The {animal} pressed its nose to the frosty window. Outside, the first snow "
          f"of winter spun down in lazy circles. With a happy leap, the {animal} darted "
          f"for the door — some things are just too magical to watch from inside."),
         (f"The {animal} makes a 'happy leap' toward the snow, too excited to stay inside "
          f"— that shows eagerness and curiosity, not fear or boredom.")),
    ])
    animal_q = {
        "category": "reading", "type": "mc",
        "question": f"What best describes the {animal} in the passage?",
        "passage": passage,
        "options": [f"A. Bored and sleepy", f"B. Curious and adventurous",
                    f"C. Scared and hiding", f"D. Hungry and grumpy"],
        "answer": "B",
        "explanation": explanation,
    }
    return [food_q, animal_q]


def sample(n, la_count, mastered=(), review=()):
    """Pick a session's offline questions.

    Skips questions already answered correctly (`mastered`) and surfaces
    previously-missed questions (`review`) first, so a wrong answer comes
    back in a *later* session until the kid gets it right. If everything in
    a category is mastered, we fall back to the full pool so play continues.
    """
    mastered, review = set(mastered), set(review)
    la = [q for q in BANK if q["category"] != "math_challenge"]
    math = [q for q in BANK if q["category"] == "math_challenge"]

    def available(pool):
        unmastered = [q for q in pool if q["id"] not in mastered]
        return unmastered or pool

    picked = _order(available(la), review)[:la_count]
    picked += _order(available(math), review)[: n - len(picked)]
    random.shuffle(picked)
    return picked[:n]
