"""Offline fallback question bank — used when the AI is unreachable."""
import random

BANK = [
    {"category": "vocabulary", "type": "mc",
     "question": "The explorer was RELUCTANT to enter the dark cave. What does 'reluctant' mean?",
     "passage": None,
     "options": ["A. Excited", "B. Unwilling or hesitant", "C. Prepared", "D. Curious"],
     "answer": "B",
     "explanation": "'Reluctant' means hesitant or unwilling — the explorer wasn't sure they wanted to go in."},
    {"category": "grammar", "type": "mc",
     "question": "Which sentence is punctuated correctly?",
     "passage": None,
     "options": ["A. The dog barked, and the cat ran away.",
                 "B. The dog barked and, the cat ran away.",
                 "C. The dog barked, and, the cat ran away.",
                 "D. The dog, barked and the cat ran away."],
     "answer": "A",
     "explanation": "When joining two complete sentences with 'and', the comma goes before it."},
    {"category": "reading", "type": "mc",
     "question": "What is the main idea of the passage?",
     "passage": "Octopuses are escape artists of the ocean. They can squeeze through any opening larger than their beak. Aquarium workers have found them in filter pipes, other tanks, and even on the floor heading toward the sea. Some aquariums now use special lids just for octopuses.",
     "options": ["A. Octopuses have beaks.", "B. Aquariums use special lids.",
                 "C. Octopuses are remarkably good at escaping.", "D. Octopuses live in the ocean."],
     "answer": "C",
     "explanation": "Every sentence supports one big idea: octopuses escape from almost anything."},
    {"category": "figurative_language", "type": "mc",
     "question": "'The classroom was a zoo before the teacher arrived.' This is an example of:",
     "passage": None,
     "options": ["A. Simile", "B. Metaphor", "C. Personification", "D. Onomatopoeia"],
     "answer": "B",
     "explanation": "It compares the classroom to a zoo WITHOUT using 'like' or 'as' — that's a metaphor."},
    {"category": "writing_mechanics", "type": "mc",
     "question": "Which word correctly completes the sentence: 'The team celebrated ___ victory.'",
     "passage": None,
     "options": ["A. they're", "B. their", "C. there", "D. theyre"],
     "answer": "B",
     "explanation": "'Their' shows ownership — the victory belongs to the team."},
    {"category": "vocabulary", "type": "short",
     "question": "Use the word 'abundant' correctly in a sentence of your own.",
     "passage": None, "options": None,
     "answer": "Any sentence using 'abundant' to mean plentiful, e.g. 'The garden had abundant tomatoes this summer.'",
     "explanation": "'Abundant' means existing in large amounts."},
    {"category": "grammar", "type": "mc",
     "question": "Identify the subject of this sentence: 'After the storm, the soccer field flooded completely.'",
     "passage": None,
     "options": ["A. storm", "B. the soccer field", "C. flooded", "D. completely"],
     "answer": "B",
     "explanation": "Ask 'what flooded?' The soccer field — that's the subject."},
    {"category": "reading", "type": "short",
     "question": "Based on the passage, why do you think Maya kept checking her watch?",
     "passage": "Maya kept checking her watch as she waited at the bus stop. Her science fair project — a volcano that actually smoked — sat carefully balanced on her lap. Judging started at nine o'clock sharp, and the bus was already six minutes late.",
     "options": None,
     "answer": "She was worried about being late to the science fair judging because the bus was running late.",
     "explanation": "The clues: judging starts at nine, the bus is late — she's nervous about missing it."},
    {"category": "figurative_language", "type": "short",
     "question": "Write your own simile describing how fast a cheetah runs.",
     "passage": None, "options": None,
     "answer": "Any comparison using 'like' or 'as', e.g. 'The cheetah ran like lightning across the plain.'",
     "explanation": "A simile compares two things using 'like' or 'as'."},
    {"category": "math_challenge", "type": "mc",
     "question": "A game costs $48. It goes on sale for 25% off, then you have a coupon for $5 off the sale price. What do you pay?",
     "passage": None,
     "options": ["A. $31", "B. $36", "C. $38", "D. $43"],
     "answer": "A",
     "explanation": "25% of 48 is 12, so the sale price is $36. Minus the $5 coupon = $31."},
    {"category": "math_challenge", "type": "mc",
     "question": "Two hoses fill a pool. Hose A fills it alone in 6 hours; Hose B in 3 hours. Together, how long?",
     "passage": None,
     "options": ["A. 4.5 hours", "B. 2 hours", "C. 3 hours", "D. 1.5 hours"],
     "answer": "B",
     "explanation": "Per hour: A fills 1/6, B fills 1/3. Together 1/6 + 2/6 = 3/6 = half the pool per hour → 2 hours."},
    {"category": "math_challenge", "type": "mc",
     "question": "A recipe uses 3 cups of flour for every 2 cups of sugar. You use 9 cups of flour. How much sugar?",
     "passage": None,
     "options": ["A. 4 cups", "B. 5 cups", "C. 6 cups", "D. 7 cups"],
     "answer": "C",
     "explanation": "9 flour is 3× the recipe (3→9), so sugar is also 3×: 2→6 cups."},
]


def sample(n, la_count):
    la = [q for q in BANK if q["category"] != "math_challenge"]
    math = [q for q in BANK if q["category"] == "math_challenge"]
    picked = random.sample(la, min(la_count, len(la)))
    picked += random.sample(math, min(n - len(picked), len(math)))
    random.shuffle(picked)
    return picked[:n]
